#!/bin/bash

#cunningly make it take either one arg or no arg - 
#one arg -> series name -> append to front of file name
#no args -> just strip out the chars

for FILE in *.ogm;
do NEWFILE=$FILE
 if [ -n "$1" ]
 then
 NEWFILE=$1$FILE
 fi
 echo "$FILE will be renamed as $NEWFILE" ;
 mv "$FILE" "$NEWFILE" ;
done
