#!/bin/bash

#cunningly make it take either one arg or no arg - 
#one arg -> series name -> append to front of file name
#no args -> just strip out the chars

for FILE in *;
do NEWFILE=`echo $FILE | sed -e s/$1/$2/g `
 echo "$FILE will be renamed as $NEWFILE" ;
 mv "$FILE" "$NEWFILE" ;
done
