#! /usr/bin/env python
import argparse
import shutil
from sys import exit

# TODO: add options for PS1, GC
parser = argparse.ArgumentParser(description='Adds emulator games to the steam shortcuts grid')
parser.add_argument('-e', '--emulator', type=str, required=True, help='Which emulator type? (ps1/ps2/gamecube)')
parser.add_argument('-g', '--game', type=str, required=True, help='Name of game to add')
args = parser.parse_args()

# Change the below vars to the paths where your steam and pcsx2 are installed

# uncomment this if not running through cygwin 
#shortcuts = "C:\Program Files (x86)\Steam\userdata\\60545819\config\shortcuts.vdf"
shortcuts = "/cygdrive/c/Program Files (x86)/Steam/userdata/60545819/config/shortcuts.vdf"
game = args.game

# TODO per emulator
if args.emulator == "ps2":
    exe = "C:\Program Files (x86)\PCSX2 1.0.0\pcsx2-r5350.exe"
    start_directory = "C:\Program Files (x86)\PCSX2 1.0.0"
    isopath = "E:\Games\Emulators\PS2\\"
elif args.emulator == "ps1":
    exe = ""
    start_directory = ""
    isopath = ""
elif args.emulator == "gamecube":
    exe = ""
    start_directory = ""
    isopath = ""
else:
    print "Unrecognised emulator: ", args.emulator
    print "Acceptable emulator switch values are ps1 ps2 gamecube"
    exit()

print "Backing up old shortcuts file to %s" % (shortcuts + "back")
shutil.copy2(shortcuts, shortcuts+"back")

recList = []

def bytes_from_file(filename):
    with open(filename, "rb") as f:
        while True:
            chunk = f.read()
            if chunk:
                for b in chunk:
                    yield b
            else:
                break

def readShortcuts():

    parseRow= True
    parseKey = False
    parseValue = False
    record = 0
    d = {}
    keybuf = ""
    valbuf = ""

    for b in bytes_from_file(shortcuts):

        # seeking record
        if(parseRow and (b == '\b')):
            parseRow = False
            recList.append(dict(d))
            d.clear()
            continue
        
        # parsing
        if(parseKey):
            if(b == '\00'):
                parseKey = False
                parseValue = True
            else:
                keybuf += b
            continue

        if(parseValue):
            if(b == '\00'):
                parseValue = False
                # add key+val+record to dict, clear buffers, 
                if keybuf in ("AppName", "Exe", "StartDir", "0"):
                    if(keybuf == "0"): keybuf = "Category"
                    d[keybuf] = valbuf
                keybuf = ""
                valbuf = ""
            else:
                valbuf += b
            continue
                
        if (b == '\01'):
            parseKey = True
            if(parseRow == False):
                parseRow = True
                record = record+1
            continue

def writeNewShortcuts():
    out = ""
    r = 0
    # header
    out += "\00shortcuts\00"
    # list of shortcuts
    for s in recList:
        out += "\00" + str(r) + "\00" + "\01AppName\00" + s['AppName'] + "\00"
        out += "\01Exe\00" + s['Exe'] + "\00"
        out += "\01StartDir\00" + s['StartDir'] + "\00"
        out += "\01icon\00\00\00tags\00"
        if s.has_key('Category'):
            out += "\01" + str(0) + "\00" + s['Category'] + "\00"
        out += "\b\b"
        r+=1
    # footer
    out += "\b\b"

    outfile = open(shortcuts, 'wb')
    outfile.write(out)


def enqoute(s):
    return "\"" + s + "\""

try:
    readShortcuts()
except: # TODO catch an actual exception you dummy
    print "There was a problem reading the shortcuts file"

# add new entries
e = {}
e['AppName'] = game
e['Exe'] = enqoute(exe) + " " + enqoute(isopath + game + "\\" + game + ".iso") + " --cfgpath=" + enqoute(isopath + game + "\\" + "inis") +" --nogui --fullscreen"
e['StartDir'] = enqoute(start_directory)
e['Category'] = "Emulator"
print isopath
print e
recList.append(dict(e))

writeNewShortcuts()
