#!/bin/bash
# Convert filenames to lowercase
# and replace characters recursively
#####################################

if [ -z $1 ];then echo Give target directory; exit 0;fi

find "$1" -depth -name '*' | while read file ; do
    directory=$(dirname "$file")
	oldfilename=$(basename "$file")
	BASENAME=${file%.*}
    FILETYPE=${file##*.}
    if [ -d $file ];
    # directories
    then newfilename=$(echo "$oldfilename" | tr 'A-Z' 'a-z' | tr ' ' '_' | sed 's/_-_/-/g' | sed 's/-/_/g' | sed 's/\./_/g')
        if [ "$oldfilename" != "$newfilename" ]; then
                #mv -i "$directory/$oldfilename" "$directory/$newfilename"
                echo ""$directory/$oldfilename" ---> "$directory/$newfilename""
        fi
    # files
    else newfilename=$(echo "$BASENAME" | tr 'A-Z' 'a-z' | tr ' ' '_' | sed 's/_-_/-/g' | sed 's/-/_/g' | sed 's/\./_/g').$FILETYPE
        if [ "$oldfilename" != "$newfilename" ]; then
                ##mv -i "$directory/$oldfilename" "$newfilename"
                echo ""$directory/$oldfilename" ---> "$newfilename""
        fi
    fi
        done
exit 0
